// Generated By Abdullah Hameed
import 'package:fynd/feature/posts/domain/entities/post_entity.dart';
import 'package:fynd/feature/posts/domain/repositories/posts_repository.dart';

class GetRecentPostsUseCase {
  final PostsRepository repository;

  GetRecentPostsUseCase(this.repository);
  Future<List<PostEntity>> call() async {
    return await repository.getRecentPosts();
  }
}
