// Generated By Abdullah Hameed
import 'package:fynd/feature/home/domain/entities/recent_post_entity.dart';
import 'package:fynd/feature/posts/domain/repositories/posts_repository.dart';

class GetRecentPostsUseCase {
  final PostsRepository repository;

  GetRecentPostsUseCase(this.repository);
  Future<List<RecentPostEntity>> call() async {
    return await repository.getRecentPosts();
  }
}
