// Generated By Abdullah Hameed
import 'package:fynd/feature/posts/domain/params/post_filter.dart';
import 'package:fynd/feature/posts/domain/entities/post_response_entity.dart';
import 'package:fynd/feature/posts/domain/repositories/posts_repository.dart';

class GetPostsUseCase {
  final PostsRepository repository;
  GetPostsUseCase(this.repository);

  Future<PostResponseEntity> call(PostFilter filter) async {
    return await repository.getPosts(filter);
  }
}
