// Generated By Abdullah Hameed
import 'package:fynd/feature/posts/domain/entities/post_response_entity.dart';
import 'package:fynd/feature/posts/domain/repositories/posts_repository.dart';

class GetMyPostsUseCase {
  final PostsRepository repository;
  GetMyPostsUseCase(this.repository);

  Future<PostResponseEntity> call() async {
    return await repository.getMyPosts();
  }
}
