/// Generated By Abdullah Hameed

class PostsEntity {
  final String id;

  const PostsEntity({
    required this.id,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PostsEntity &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'PostsEntity(id: $id)';
}
