import 'package:fynd/feature/home/domain/entities/category_entity.dart';
import 'package:fynd/feature/posts/domain/params/post_filter.dart';
import 'package:fynd/feature/posts/domain/entities/post_entity.dart';
import 'package:fynd/feature/posts/domain/entities/post_response_entity.dart';

/// Generated By Abdullah Hameed

abstract class PostsRepository {
  Future<List<PostEntity>> getRecentPosts();

  Future<PostResponseEntity> getPosts(PostFilter filter);

  Future<List<CategoryEntity>> getCategories();

  Future<void> createPost({required Map<String, dynamic> data});
}
