/// Generated By Abdullah Hameed
import 'package:fynd/feature/home/data/models/recent_post_model.dart';
import 'package:fynd/feature/home/domain/entities/recent_post_entity.dart';
// import 'package:fynd/feature/posts/data/models/recent_post_model.dart';
import 'package:fynd/feature/posts/domain/repositories/posts_repository.dart';
import 'package:fynd/feature/posts/data/datasources/posts_remote_data_source.dart';

class PostsRepositoryImpl implements PostsRepository {
  final PostsRemoteDataSource remoteDataSource;

  PostsRepositoryImpl({required this.remoteDataSource});

  @override
  Future<List<RecentPostEntity>> getRecentPosts() async {
    final response = await remoteDataSource.getRecentPosts();

    final recentPosts = (response.data as List)
        .map((item) => RecentPostModel.fromMap(item))
        .toList();

    return recentPosts.map((post) => post.toEntity()).toList();
  }
}
