/// Generated By Abdullah Hameed
import '../../domain/entities/posts_entity.dart';

class PostsModel {
  final String id;

  const PostsModel({
    required this.id,
  });

  /// Convert from Model to Entity
  PostsEntity toEntity() {
    return PostsEntity(id: id);
  }

  /// Convert from JSON
  factory PostsModel.fromJson(Map<String, dynamic> json) {
    return PostsModel(
      id: json['id'] ?? '',
    );
  }

  /// Convert to JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
    };
  }
}
