import 'package:dio/dio.dart';
import 'package:fynd/core/network/api_endpoints.dart';
import 'package:fynd/core/network/network_client.dart';

/// Generated By Abdullah Hameed

abstract class PostsRemoteDataSource {
  Future<Response> getRecentPosts();
}

class PostsRemoteDataSourceImpl implements PostsRemoteDataSource {
  @override
  Future<Response> getRecentPosts() {
    return NetworkClient.get(url: ApiEndpoints.recentPosts);
  }
}
