import 'package:dio/dio.dart';
import 'package:fynd/core/network/api_endpoints.dart';
import 'package:fynd/core/network/network_client.dart';
import 'package:fynd/feature/posts/domain/params/post_filter.dart';

/// Generated By Abdullah Hameed

abstract class PostsRemoteDataSource {
  Future<Response> getRecentPosts();

  Future<Response> getPosts(PostFilter filter);

  Future<Response> getCategories();

  Future<Response> createPost({required Map<String, dynamic> data});

  Future<Response> getMyPosts();

  Future<Response> getPostDetails({required int postId, required int postType});
}

class PostsRemoteDataSourceImpl implements PostsRemoteDataSource {
  @override
  Future<Response> getRecentPosts() {
    return NetworkClient.get(url: ApiEndpoints.recentPosts);
  }

  @override
  Future<Response> getPosts(PostFilter filter) {
    return NetworkClient.get(
      url: ApiEndpoints.posts,
      queryParameters: {
        'page': filter.page,
        if (filter.search != null && filter.search!.isNotEmpty)
          'search': filter.search,

        if (filter.categoryId != null) 'categoryId': filter.categoryId,

        if (filter.type != null) 'type': filter.type,

        if (filter.location != null && filter.location!.isNotEmpty)
          'location': filter.location,
      },
    );
  }

  @override
  Future<Response<dynamic>> getCategories() {
    return NetworkClient.get(url: ApiEndpoints.categories);
  }

  @override
  Future<Response<dynamic>> createPost({required Map<String, dynamic> data}) {
    return NetworkClient.post(url: ApiEndpoints.createPost, data: data);
  }

  @override
  Future<Response<dynamic>> getMyPosts() {
    return NetworkClient.get(url: ApiEndpoints.myPosts);
  }

  @override
  Future<Response<dynamic>> getPostDetails({
    required int postId,
    required int postType,
  }) {
    return NetworkClient.get(
      url: ApiEndpoints.postDetails,
      queryParameters: {'id': postId, 'type': postType},
    );
  }
}
