/// Generated By Abdullah Hameed

abstract class PostsLocalDataSource {
  // Add your local storage methods here
}

class PostsLocalDataSourceImpl implements PostsLocalDataSource {
  // Add your implementation here
}
