/// Generated By Abdullah Hameed
import 'package:flutter/material.dart';

/// Widget for posts

class PostsWidget extends StatelessWidget {
  const PostsWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      // Add your UI here
      child: const Text('posts Widget'),
    );
  }
}
